### PR TITLE
Newline fix - the .js part

### PR DESCRIPTION
**Pull request by biziclop**
Sorry, I forgot to update admin.js to mirror changes in the .php file.

### CODE REVIEW

**Comment by j-ro** [comment]
awesome, thanks -- how exactly would I test this? The current version with your other fix seems to preserve comments just fine for me. So just looking for how to reproduce the bug so I can check things out a bit.

**Comment by biziclop** [comment]
Hi, simply make a new post, go to html editor type aaa<enter>bbb then switch to the visual editor, and you will see aaabbb, because it would be the javascript part's responsibility to fix it. I tested it in Mac Safari & Firefox.

**Comment by j-ro** [comment]
hm...I tried out the new js on my local, and typing aaabbb and switching to visual showed aaabbbb in both situations, which I think is correct behavior anyway?

**Comment by biziclop** [comment]
This isn't my day, i wanted to write aaa[enter]bbb, but the editor ate the < > symbols.

**Comment by j-ro** [comment]
ah, gotcha.

so, now, in the HTML side, I type:

```
aaa
bbb
```

On the visual side I see:

```
aaabbb
```

flip back to html side, I see:

```
aaa
bbb
```

Which is how it worked before I think. And how it should work -- this plugin disables the auto p/br tag adding for new lines on purpose.

**Comment by biziclop** [comment]
Auto p/br disabling is perfectly fine, but glueing two distinct words separated by newlines into one isn't. I discovered this problem when I copied some hard-wrapped text from an email to the html editor, and I wondered whyTF some words got stuck together in the visual editor.

**Comment by j-ro** [comment]
ah, gotcha. indeed, that's not good behavior. Unfortunately, at least for me, this pull doesn't fix it...

**Comment by j-ro** [comment]
aaand, I just upgraded to WP 4.1 and your fix works just fine. I'll push it out.

**Comment by biziclop** [comment]
Ok, I hope it doesn't introduce new problems :)

**Comment by j-ro** [comment]
we shall see! Either way, thanks for the help!

**Pull request merged**
